apiVersion: apps/v1
kind: Deployment
metadata:
  name: almworkshop-advanced
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: almworkshop-advanced
  template:
    metadata:
      labels:
        app: almworkshop-advanced
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: almworkshop-advanced
        ports:
        - containerPort: 80
